### PR TITLE
Statistics

### PR DESCRIPTION
**Pull request by Matarraa**
Changed files:
1) base.html
2) style.css

New files:
1) statistics.js
2) statistics.html

### CODE REVIEW

**Comment by bast** [comment]
Thanks! I am now reviewing this.

**Comment by bast** [comment]
One file was missing but the local preview looks good.

From my point of view this looks good and is a very nice improvement. @Labrus do you agree with this change? I assume you have context about this change but if not, then I or the submitter can describe it?

**Comment by Labrus** [comment]
I agree with this additional feature to give the updated overview of the
distribution of different types of constructions. Our student Tatiana
Perevoshchikova worked hard on this code. Please let me know what file is
missing, as far as I understood she submitted the full version to the best
of her mind. anna

man. 25. apr. 2022, 10:21 skrev Radovan Bast ***@***.***>:

**Comment by bast** [comment]
I have added the missing file (see further up in the GitHub discussion thread).

**Comment by Labrus** [comment]
Wow, this looks so good now! Thank you!
Anna

**Pull request merged**
